stages:          
  - check
check_nginx:
    stage: check
    script:
        - which nginx || echo "nginx не установлен" && exit 1
        - nginx -v 
    tags:
        - shell # выполнение через шелл раннер на домашнем пк
                # в дальнейшем я там докер образ написал, можно запускаться через него, но не уверен, что именно требуется
